### ISSUE TITLE
Can not install pyModis via pip

### ISSUE THREAD

**Issue by superhaoshuai** [lucadelu/pyModis#103]
Traceback (most recent call last):
      File "/private/var/folders/vf/fl25g7pn5bd54fzqqrcq4wc40000gn/T/pip-build-fgvf4yrh/GDAL/setup.py", line 131, in fetch_config
        p = subprocess.Popen([command, args], stdout=subprocess.PIPE)
      File "/Users/haoshuai/anaconda2/envs/py34/lib/python3.4/subprocess.py", line 859, in __init__
        restore_signals, start_new_session)
      File "/Users/haoshuai/anaconda2/envs/py34/lib/python3.4/subprocess.py", line 1457, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: '../../apps/gdal-config'
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "/private/var/folders/vf/fl25g7pn5bd54fzqqrcq4wc40000gn/T/pip-build-fgvf4yrh/GDAL/setup.py", line 179, in get_gdal_config
        return fetch_config(option, gdal_config = self.gdal_config)
      File "/private/var/folders/vf/fl25g7pn5bd54fzqqrcq4wc40000gn/T/pip-build-fgvf4yrh/GDAL/setup.py", line 135, in fetch_config
        raise gdal_config_error(e)
    __main__.gdal_config_error: [Errno 2] No such file or directory: '../../apps/gdal-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/private/var/folders/vf/fl25g7pn5bd54fzqqrcq4wc40000gn/T/pip-build-fgvf4yrh/GDAL/setup.py", line 131, in fetch_config
        p = subprocess.Popen([command, args], stdout=subprocess.PIPE)
      File "/Users/haoshuai/anaconda2/envs/py34/lib/python3.4/subprocess.py", line 859, in __init__
        restore_signals, start_new_session)
      File "/Users/haoshuai/anaconda2/envs/py34/lib/python3.4/subprocess.py", line 1457, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: 'gdal-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/vf/fl25g7pn5bd54fzqqrcq4wc40000gn/T/pip-build-fgvf4yrh/GDAL/setup.py", line 339, in <module>
        **extra )
      File "/Users/haoshuai/anaconda2/envs/py34/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/haoshuai/anaconda2/envs/py34/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Users/haoshuai/anaconda2/envs/py34/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/haoshuai/anaconda2/envs/py34/lib/python3.4/site-packages/setuptools-18.5-py3.4.egg/setuptools/command/egg_info.py", line 180, in run
      File "/Users/haoshuai/anaconda2/envs/py34/lib/python3.4/site-packages/setuptools-18.5-py3.4.egg/setuptools/command/egg_info.py", line 207, in find_sources
      File "/Users/haoshuai/anaconda2/envs/py34/lib/python3.4/site-packages/setuptools-18.5-py3.4.egg/setuptools/command/egg_info.py", line 291, in run
      File "/Users/haoshuai/anaconda2/envs/py34/lib/python3.4/site-packages/setuptools-18.5-py3.4.egg/setuptools/command/egg_info.py", line 320, in add_defaults
      File "/Users/haoshuai/anaconda2/envs/py34/lib/python3.4/site-packages/setuptools-18.5-py3.4.egg/setuptools/command/sdist.py", line 130, in add_defaults
      File "/Users/haoshuai/anaconda2/envs/py34/lib/python3.4/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/Users/haoshuai/anaconda2/envs/py34/lib/python3.4/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/private/var/folders/vf/fl25g7pn5bd54fzqqrcq4wc40000gn/T/pip-build-fgvf4yrh/GDAL/setup.py", line 214, in finalize_options
        self.gdaldir = self.get_gdal_config('prefix')
      File "/private/var/folders/vf/fl25g7pn5bd54fzqqrcq4wc40000gn/T/pip-build-fgvf4yrh/GDAL/setup.py", line 188, in get_gdal_config
        return fetch_config(option)
      File "/private/var/folders/vf/fl25g7pn5bd54fzqqrcq4wc40000gn/T/pip-build-fgvf4yrh/GDAL/setup.py", line 135, in fetch_config
        raise gdal_config_error(e)
    __main__.gdal_config_error: [Errno 2] No such file or directory: 'gdal-config'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/vf/fl25g7pn5bd54fzqqrcq4wc40000gn/T/pip-build-fgvf4yrh/GDAL/

**Comment by lucadelu** [comment]
Hi @superhaoshuai, 

Are you running installation in a MAC OS right? 

Did you try to install the GDAL package (maybe also the python-gdal package) and later run the pyModis installation?

**Comment by lucadelu** [comment]
You can also use pygdal, this should solve the problem.

Reopen if needed
