### ISSUE TITLE
netrc file no longer recognized

### ISSUE THREAD

**Issue by veroandreo** [lucadelu/pyModis#137]
Were there any changes regarding netrc file? It's no longer recognized

```
13:31 $ modis_download.py -s MOLT -p MOD13C2.006 -f 2014-10-01 -e 2015-01-01 .
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyModis-2.2.0-py3.9.egg/pymodis/downmodis.py", line 267, in __init__
  File "/usr/lib64/python3.9/netrc.py", line 30, in __init__
    self._parse(file, fp, default_netrc)
  File "/usr/lib64/python3.9/netrc.py", line 104, in _parse
    raise NetrcParseError(
netrc.NetrcParseError: ~/.netrc access too permissive: access permissions must restrict access to only the owner (/home/veroandreo/.netrc, line 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/modis_download.py", line 4, in <module>
    __import__('pkg_resources').run_script('pyModis==2.2.0', 'modis_download.py')
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1470, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.9/site-packages/pyModis-2.2.0-py3.9.egg/EGG-INFO/scripts/modis_download.py", line 153, in <module>
  File "/usr/local/lib/python3.9/site-packages/pyModis-2.2.0-py3.9.egg/EGG-INFO/scripts/modis_download.py", line 135, in main
  File "/usr/local/lib/python3.9/site-packages/pyModis-2.2.0-py3.9.egg/pymodis/downmodis.py", line 269, in __init__
OSError: Please set 'user' and 'password' parameters, netrc file does not exist
```
I changed permissions, but I keep getting the same error message

**Comment by neteler** [comment]
Note that the permission need to be `-rw-------`, anything else may lead to the problem above.

(yes, error catching might be improved...)

**Comment by veroandreo** [comment]
now it works, thanks!
