### ISSUE TITLE
Why I am getting the error </head> doesn't have matching <head>>

### ISSUE THREAD

**Issue by manapshymyr-OB** [lucadelu/pyModis#139]
I am trying to create a mosaic with tiles from MODIS data. Logfile shows that all data are downloaded correctly. Unfortunately I am getting the following error:

`D:\Internship\MOLT\MOD13Q1.006\2021.04.07\MOD13Q1.A2021097.h21v03.006.2021115205047.hdf
Traceback (most recent call last):
  File "C:/Users/Gigabyte/PycharmProjects/CAMP4ASB/raster_data_download.py", line 382, in <module>
    create_mosaic(files,product_name)
  File "C:/Users/Gigabyte/PycharmProjects/CAMP4ASB/raster_data_download.py", line 247, in create_mosaic
    mosaic = convertmodis_gdal.createMosaicGDAL(hdf_files,layers)
  File "C:\Users\Gigabyte\PycharmProjects\pythonProject\DSP\lib\site-packages\pymodis\convertmodis_gdal.py", line 503, in __init__
    self._initLayers()
  File "C:\Users\Gigabyte\PycharmProjects\pythonProject\DSP\lib\site-packages\pymodis\convertmodis_gdal.py", line 512, in _initLayers
    src_ds = gdal.Open(self.in_names[0])
  File "C:\Users\Gigabyte\PycharmProjects\pythonProject\DSP\lib\site-packages\osgeo\gdal.py", line 4176, in Open
    return _gdal.Open(*args)
RuntimeError: Line 76: </head> doesn't have matching <head>.`

`GDAL Version: 3.2.1`

Can you please share your thoughts?

**Comment by manapshymyr-OB** [comment]
> I am trying to create a mosaic with tiles from MODIS data. Logfile shows that all data are downloaded correctly. Unfortunately I am getting the following error:
> 
> `D:\Internship\MOLT\MOD13Q1.006\2021.04.07\MOD13Q1.A2021097.h21v03.006.2021115205047.hdf Traceback (most recent call last): File "C:/Users/Gigabyte/PycharmProjects/CAMP4ASB/raster_data_download.py", line 382, in <module> create_mosaic(files,product_name) File "C:/Users/Gigabyte/PycharmProjects/CAMP4ASB/raster_data_download.py", line 247, in create_mosaic mosaic = convertmodis_gdal.createMosaicGDAL(hdf_files,layers) File "C:\Users\Gigabyte\PycharmProjects\pythonProject\DSP\lib\site-packages\pymodis\convertmodis_gdal.py", line 503, in __init__ self._initLayers() File "C:\Users\Gigabyte\PycharmProjects\pythonProject\DSP\lib\site-packages\pymodis\convertmodis_gdal.py", line 512, in _initLayers src_ds = gdal.Open(self.in_names[0]) File "C:\Users\Gigabyte\PycharmProjects\pythonProject\DSP\lib\site-packages\osgeo\gdal.py", line 4176, in Open return _gdal.Open(*args) RuntimeError: Line 76: </head> doesn't have matching <head>.`
> 
> `GDAL Version: 3.2.1`
> 
> Can you please share your thoughts?

@lucadelu
