### ISSUE TITLE
error when running pymodis with python 3.9 nor 3.10

### ISSUE THREAD

**Issue by veroandreo** [lucadelu/pyModis#143]
Asking for help with eg. `modis_download.py --h` or trying to run any other pymodis module, yields the following error both in a laptop with python 3.9 and a different one with python 3.10 (fedora 35 and 34 respectivelly): 
```
modis_download.py --help
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pyModis 2.1.0 (/home/veroandreo/.local/lib/python3.10/site-packages), Requirement.parse('pyModis==2.0.9'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/modis_download.py", line 4, in <module>
    __import__('pkg_resources').run_script('pyModis==2.0.9', 'modis_download.py')
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 583, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyModis==2.0.9' distribution was not found and is required by the application
```
Meanwhile, there were no errors when installing pymodis via `pip3 install -U pymodis` nor when importing the library in a python terminal. Moreover, when installing as described, I get pymodis 2.1.0, but in the error it keeps asking for 2.0.9.

Also the website is unreachable at time.

Am I doing something wrong?

**Comment by veroandreo** [comment]
Installing tag 2.2.0 from source solves it. Would be cool to get this version from pip instead of 2.1.0, if it is in fact something version related

**Comment by lucadelu** [comment]
New version released, could be closed?

**Comment by veroandreo** [comment]
yes, closing
