### ISSUE TITLE
I can't get pymodis in my vscode

### ISSUE THREAD

**Issue by tksoueu** [lucadelu/pyModis#144]
Everytime i try to get pymodis in my vscode (using WSL) it gives me this error, can anyone help me?

ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-a0vf1ae1/GDAL/setup.py'"'"'; __file__='"'"'/tmp/pip-install-a0vf1ae1/GDAL/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-a0vf1ae1/GDAL/pip-egg-info
         cwd: /tmp/pip-install-a0vf1ae1/GDAL/
    Complete output (116 lines):
    running egg_info
    creating /tmp/pip-install-a0vf1ae1/GDAL/pip-egg-info/GDAL.egg-info
    writing manifest file '/tmp/pip-install-a0vf1ae1/GDAL/pip-egg-info/GDAL.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "/tmp/pip-install-a0vf1ae1/GDAL/setup.py", line 105, in fetch_config
        p = subprocess.Popen([command, args], stdout=subprocess.PIPE)
      File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: '../../apps/gdal-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-a0vf1ae1/GDAL/setup.py", line 188, in get_gdal_config
        return fetch_config(option, gdal_config=self.gdal_config)
      File "/tmp/pip-install-a0vf1ae1/GDAL/setup.py", line 108, in fetch_config
        raise gdal_config_error(e)
    __main__.gdal_config_error: [Errno 2] No such file or directory: '../../apps/gdal-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-a0vf1ae1/GDAL/setup.py", line 105, in fetch_config
        p = subprocess.Popen([command, args], stdout=subprocess.PIPE)
      File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'gdal-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-a0vf1ae1/GDAL/setup.py", line 195, in get_gdal_config
        return fetch_config(option)
      File "/tmp/pip-install-a0vf1ae1/GDAL/setup.py", line 108, in fetch_config
        raise gdal_config_error(e)
    __main__.gdal_config_error: [Errno 2] No such file or directory: 'gdal-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-a0vf1ae1/GDAL/setup.py", line 389, in <module>
        setup(**setup_kwargs)
      File "/home/tksoueu/.local/lib/python3.8/site-packages/setuptools/__init__.py", line 155, in setup
        return distutils.core.setup(**attrs)
      File "/home/tksoueu/.local/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
        return run_commands(dist)
      File "/home/tksoueu/.local/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
        dist.run_commands()
      File "/home/tksoueu/.local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
        self.run_command(cmd)
      File "/home/tksoueu/.local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/home/tksoueu/.local/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 299, in run
        self.find_sources()
      File "/home/tksoueu/.local/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 306, in find_sources
        mm.run()
      File "/home/tksoueu/.local/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 541, in run
        self.add_defaults()
      File "/home/tksoueu/.local/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 578, in add_defaults
        sdist.add_defaults(self)
      File "/home/tksoueu/.local/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 228, in add_defaults
        self._add_defaults_ext()
      File "/home/tksoueu/.local/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 311, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "/home/tksoueu/.local/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/home/tksoueu/.local/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/tmp/pip-install-a0vf1ae1/GDAL/setup.py", line 258, in finalize_options
        self.gdaldir = self.get_gdal_config('prefix')
      File "/tmp/pip-install-a0vf1ae1/GDAL/setup.py", line 201, in get_gdal_config
        raise gdal_config_error(traceback_string + '\n' + msg)
    __main__.gdal_config_error: Traceback (most recent call last):
      File "/tmp/pip-install-a0vf1ae1/GDAL/setup.py", line 105, in fetch_config
        p = subprocess.Popen([command, args], stdout=subprocess.PIPE)
      File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: '../../apps/gdal-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-a0vf1ae1/GDAL/setup.py", line 188, in get_gdal_config
        return fetch_config(option, gdal_config=self.gdal_config)
      File "/tmp/pip-install-a0vf1ae1/GDAL/setup.py", line 108, in fetch_config
        raise gdal_config_error(e)
    gdal_config_error: [Errno 2] No such file or directory: '../../apps/gdal-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-a0vf1ae1/GDAL/setup.py", line 105, in fetch_config
        p = subprocess.Popen([command, args], stdout=subprocess.PIPE)
      File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'gdal-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-a0vf1ae1/GDAL/setup.py", line 195, in get_gdal_config
        return fetch_config(option)
      File "/tmp/pip-install-a0vf1ae1/GDAL/setup.py", line 108, in fetch_config
        raise gdal_config_error(e)
    gdal_config_error: [Errno 2] No such file or directory: 'gdal-config'
    
    Could not find gdal-config. Make sure you have installed the GDAL native library and development headers.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by lucadelu** [comment]
Is `gdal-config` installed?

**Comment by tksoueu** [comment]
i had to install every single dependencies one by one xd
