### ISSUE TITLE
Error running modis_download.py 

### ISSUE THREAD

**Issue by veroandreo** [lucadelu/pyModis#156]
I installed pymodis from source yesterday (2.4.0) and when I try to run `modis_download.py -h` or `modis_download.py --help`, I get the following error:
```
modis_download.py --help
Traceback (most recent call last):
  File "/usr/local/bin/modis_download.py", line 4, in <module>
    __import__('pkg_resources').run_script('pyModis==2.4.0', 'modis_download.py')
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1479, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.11/site-packages/pyModis-2.4.0-py3.11.egg/EGG-INFO/scripts/modis_download.py", line 167, in <module>
  File "/usr/local/lib/python3.11/site-packages/pyModis-2.4.0-py3.11.egg/EGG-INFO/scripts/modis_download.py", line 58, in main
  File "/usr/lib64/python3.11/optparse.py", line 1000, in add_option
    option = self.option_class(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyModis-2.4.0-py3.11.egg/pymodis/optparse_required.py", line 48, in __init__
  File "/usr/lib64/python3.11/optparse.py", line 570, in __init__
    self._set_opt_strings(opts)
  File "/usr/lib64/python3.11/optparse.py", line 607, in _set_opt_strings
    raise OptionError(
optparse.OptionError: invalid long option string '-token': must start with --, followed by non-dash
```
I understand there have been changes with a new authorization process involving a token, and I see there was a change applied for that (#148), but neither the change nor the new usage was documented. What I understand from the mentioned PR is that the access via .netrc file should still be supported, but when I try to run a command to download data (eg.: `modis_download.py -s MOTA -p MCD12Q1.061 -t h13v11 -f 2010-01-01 -e 2001-01-01 .`), I get the same error as above. So, basically nothing works for the function `modis_download.py`. The other functions seem to work as expected though, so I assume it is something related to the last change regarding the token support. 

@lucadelu @anton-petrov any hints?? How should we run modis_download.py now?

**Comment by anton-petrov** [comment]
Ok, it seems, we need to add support for a new parameter `token` to the command line. Will do that in the near time.

**Comment by veroandreo** [comment]
> Ok, it seems, we need to add support for a new parameter `token` to the command line. Will do that in the near time.

That'd be awesome, much appreciated!

**Comment by anton-petrov** [comment]
@veroandreo 
https://github.com/lucadelu/pyModis/pull/157
