### ISSUE TITLE
wx dependency is missing

### ISSUE THREAD

**Issue by markusuwe** [lucadelu/pyModis#18]
I compiled pymodis from source following these instructions: http://pymodis.fem-environment.eu/info.html#compile-from-source
I have python 2.7.7, numpy 1.8.1 and gdal 1.11.1 also installed. After I was finished I tried to import pymodis:
>>>
[markus.mueller@build-gpu-p pyModis]$ python
Python 2.7.7 (default, Jun 18 2014, 14:29:08) 
[GCC Intel(R) C++ gcc 4.4 mode] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymodis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pymodis/__init__.py", line 1, in <module>
    import downmodis, parsemodis, convertmodis, optparse_required, optparse_gui, qualitymodis, convertmodis_gdal
  File "pymodis/optparse_gui.py", line 14, in <module>
    import wx
ImportError: No module named wx

It seems that wxpython is an additional but not documented dependency. As additional information: I work on a linux cluster and am not interested in the GUI.

Any help appreciated

**Comment by emmikb** [comment]
I have downloaded the most recent version of pyModis and am still having issues with pymodis' recognition of wxpython.  
`import pymodis

Traceback (most recent call last):
  File "<pyshell#18>", line 1, in <module>
    import pymodis
  File "build\bdist.win-amd64\egg\pymodis\__init__.py", line 8, in <module>
  File "build\bdist.win-amd64\egg\pymodis\optparse_gui.py", line 58, in <module>
NameError: name 'wx' is not defined`

I have installed wxpython 3.0 _ py27.0

**Comment by lucadelu** [comment]
Thanks for the bug report.
In e7aa44b I should fixed the problem. Could you please can test it?

If you notice any problems with wxpython 3.0 (I think you will find some) please report them in new issue. Thanks

**Comment by acoupin** [comment]
Hello,
The bug isn't fixed. In __init__.py, error raised is a NameError error (see below), although try..except protects from ImportError.

>>> import pymodis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\python27\lib\site-packages\pymodis\__init__.py", line 8, in <module>
    import optparse_gui
  File "c:\python27\lib\site-packages\pymodis\optparse_gui.py", line 58, in <mod
ule>
    class OptparseDialog(wx.Dialog):
NameError: name 'wx' is not defined

**Comment by lucadelu** [comment]
Did you use last master or 1.0.0 tag?

**Comment by acoupin** [comment]
Yes, i use last master

**Comment by lucadelu** [comment]
Please try last master, it should be fixed.

**Comment by markusuwe** [comment]
Fixed. Thanks a lot.

**Comment by herraultpa** [comment]
Dear All,

I managed to use perfectly the functions modis_download.py and modis_mosaic.py. But when I try to use modis_convert.py, I get the following error. Seems similar to this post...

modis_convert.py -s '( 1 1 1 1 1 1 1 1 1 1 1 1 )' -m /home/administrateur/MRT/ -o /home/administrateur/tmp/finalfile.tif -g 250 /home/administrateur/tmp/outputfile.hdf

(This is the example provided in pymodis.)

WxPython missing, no GUI enabled
Traceback (most recent call last):
  File "/usr/local/bin/modis_convert.py", line 166, in <module>
    main()
  File "/usr/local/bin/modis_convert.py", line 141, in main
    modisParse = parsemodis.parseModis(args[0])
  File "/usr/local/lib/python2.7/dist-packages/pymodis/parsemodis.py", line 75, in __init__
    self.tree = ElementTree.parse(f)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: XML or text declaration not at start of entity: line 1, column 166

Anyone has an idea ?

Thanks in advance

PS : I installed pymodis with pip install

Pierre

**Comment by lucadelu** [comment]
@herraultpa the problem is related to the XML file, is it present?
could you try to use modis_convert.py without MRT?

**Comment by u4sin** [comment]
I'm trying to download bulk MODIS data and I have installed pyModis and all it's dependencies yet i get the following error. 

(DDD) C:\Python27\pyModis-2.1.0\pyModis-2.1.0\scripts>modis_download_from_list.py -f G:\pyModis_snow_data\5336844369-download.txt G:\pyModis_snow_data
WxPython missing, no GUI enabled
Traceback (most recent call last):
  File "C:\Python27\pyModis-2.1.0\pyModis-2.1.0\scripts\modis_download_from_list.py", line 181, in <module>
    main()
  File "C:\Python27\pyModis-2.1.0\pyModis-2.1.0\scripts\modis_download_from_list.py", line 140, in main
    year = int(d[0:4])
ValueError: invalid literal for int() with base 10: 'ecs'
