### ISSUE TITLE
Add new -l (layers) flag to modis_parse.html + modis_multiparse.html to easily show data layers of HDF file

### ISSUE THREAD

**Issue by neteler** [lucadelu/pyModis#46]
At time it is not possible to get the data layers of a MODIS HDF file with pyModis.

A workaround is using GDAL:

```
# show included data layers
gdalinfo lst_terra.005/MOD11A1.A2016002.h18v04.005.2016023015602.hdf | grep "_NAME" | cut -d':' -f5 | nl
     1    LST_Day_1km
     2    QC_Day
     3    Day_view_time
     4    Day_view_angl
     5    LST_Night_1km
     6    QC_Night
     7    Night_view_time
     8    Night_view_angl
     9    Emis_31
    10    Emis_32
    11    Clear_day_cov
    12    Clear_night_cov
```

Such a list would be very convenient to define --subset="..." .
(example: MODIS LST: --subset="1 1 0 0 1 1 0 0 0 0 0 0")

**Comment by lucadelu** [comment]
I implemented this only to modis_parse.py but not to modis_multiparse.py because I think that should be enough get the layers from a dataset. 

Please try and let me know if it works

**Comment by lucadelu** [comment]
@neteler did you try with latest version?

**Comment by neteler** [comment]
I updated but it fails:

```
[mundialis@fedora23 lst_terra.006]$ modis_parse.py -l MOD11A1.A2012011.h18v04.006.2016103023737.hdf
1	MOD 1KM L3 LST
Traceback (most recent call last):
  File "/usr/bin/modis_parse.py", line 4, in <module>
    __import__('pkg_resources').run_script('pyModis==2.0.2', 'modis_parse.py')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1659, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/pyModis-2.0.2-py2.7.egg/EGG-INFO/scripts/modis_parse.py", line 155, in <module>
    
  File "/usr/lib/python2.7/site-packages/pyModis-2.0.2-py2.7.egg/EGG-INFO/scripts/modis_parse.py", line 141, in main
    
TypeError: cannot concatenate 'str' and 'int' objects
```

**Comment by lucadelu** [comment]
@neteler please try master after a526f86

**Comment by neteler** [comment]
Thanks, modis_parse.py works nicely. 
For multiple HDF files, one needs to run it in a loop or likewise. Closing
