### ISSUE TITLE
SyntaxError: invalid syntax : downmodis.py

### ISSUE THREAD

**Issue by dhananjaymehta** [lucadelu/pyModis#56]
Logs:
import pymodis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/anaconda/lib/python3.5/site-packages/pymodis/__init__.py", line 1, in <module>
    import downmodis
  File "~/anaconda/lib/python3.5/site-packages/pymodis/downmodis.py", line 354
    except (EOFError, ftplib.error_perm), e:

SyntaxError: invalid syntax

Solution: change  "except (EOFError, ftplib.error_perm), e:" to "except (EOFError, ftplib.error_perm) as e:"

**Comment by lucadelu** [comment]
However for Python3 you have to use branch 2.0
