### ISSUE TITLE
Catch exception if input file does not exist

### ISSUE THREAD

**Issue by neteler** [lucadelu/pyModis#65]
At time the message is a bit "wild" for standard users :-)

```
modis_parse.py -q bla
Traceback (most recent call last):
  File "/usr/bin/modis_parse.py", line 4, in <module>
    __import__('pkg_resources').run_script('pyModis==2.0.2', 'modis_parse.py')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1659, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/pyModis-2.0.2-py2.7.egg/EGG-INFO/scripts/modis_parse.py", line 155, in <module>

  File "/usr/lib/python2.7/site-packages/pyModis-2.0.2-py2.7.egg/EGG-INFO/scripts/modis_parse.py", line 110, in main

  File "build/bdist.linux-x86_64/egg/pymodis/parsemodis.py", line 65, in __init__
Exception: bla does not exist
```

Maybe easy to catch...

**Comment by lucadelu** [comment]
Done in 03b95b8, can you test it?

**Comment by neteler** [comment]
Works fine now, thanks
