### ISSUE TITLE
modis_parse.py: currently broken

### ISSUE THREAD

**Issue by neteler** [lucadelu/pyModis#66]
At time modis_parse.py does not parse anything:

```
[mundialis@fedora23 modis]$ modis_parse.py -q lst_terra.006/MOD11A1.A2012011.h18v04.006.2016103023737.hdf 
Traceback (most recent call last):
  File "/usr/bin/modis_parse.py", line 4, in <module>
    __import__('pkg_resources').run_script('pyModis==2.0.2', 'modis_parse.py')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1659, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/pyModis-2.0.2-py2.7.egg/EGG-INFO/scripts/modis_parse.py", line 155, in <module>

  File "/usr/lib/python2.7/site-packages/pyModis-2.0.2-py2.7.egg/EGG-INFO/scripts/modis_parse.py", line 134, in main

KeyError: 'QAStats'


[mundialis@fedora23 modis]$ modis_parse.py -a lst_terra.006/MOD11A1.A2012011.h18v04.006.2016103023737.hdf 
Traceback (most recent call last):
  File "/usr/bin/modis_parse.py", line 4, in <module>
    __import__('pkg_resources').run_script('pyModis==2.0.2', 'modis_parse.py')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1659, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/pyModis-2.0.2-py2.7.egg/EGG-INFO/scripts/modis_parse.py", line 155, in <module>

  File "/usr/lib/python2.7/site-packages/pyModis-2.0.2-py2.7.egg/EGG-INFO/scripts/modis_parse.py", line 134, in main

KeyError: 'QAStats'
```

**Comment by lucadelu** [comment]
@neteler should be fixed, could you confirm?

**Comment by neteler** [comment]
Yes, works, thanks.
