### ISSUE TITLE
ImportError: No module named request

### ISSUE THREAD

**Issue by GloryPassarello** [lucadelu/pyModis#95]
Hi guys, 
Many thanks for this interesting library. 
I run into an issue: i run the code called `modis_download_from_list.py` and I got that output 
````
Traceback (most recent call last):
  File "/usr/local/bin/modis_download_from_list.py", line 30, in <module>
    from pymodis import downmodis
  File "/usr/local/lib/python2.7/dist-packages/pymodis/__init__.py", line 3, in <module>
    from . import downmodis
  File "/usr/local/lib/python2.7/dist-packages/pymodis/downmodis.py", line 53, in <module>
    from urllib.request import urlopen
ImportError: No module named request
````

I installed `pyModis` using `pip`
I have `Python 2.7.12` on Ubuntu `16.04 LTS` 

If I run in python console: 
 ````
try:
    from urllib.request import urlopen
except ImportError:
    from urllib2 import urlopen
````

no error appears. 

How could I solve this?

**Comment by lucadelu** [comment]
Please update pyModis version to 2.0.8
