### ISSUE TITLE
It does not work for me

### ISSUE THREAD

**Issue by GloryPassarello** [lucadelu/pyModis#96]
Hi everyone, 
I tried to run this 
`modis_download_from_list.py -u https://e4ftl01.cr.usgs.gov/MOTA/MCD12Q1.051/2013.01.01/ -U ##### -P ###### -p MCD12Q1.051  -f  ~/modis_download/MODTiles.txt ~/modis_download/output`
but it is not working for me. 
I've got this output:
```
> /usr/local/bin/modis_download_from_list.py(104)main()
-> tiles = [elem.strip().split('.')[2] for elem in lines if elem != '\n']
(Pdb)
```
After typing c, I got:

```
Traceback (most recent call last):
  File "/usr/local/bin/modis_download_from_list.py", line 134, in <module>
    main()
  File "/usr/local/bin/modis_download_from_list.py", line 104, in main
    tiles = [elem.strip().split('.')[2] for elem in lines if elem != '\n']
  File "/usr/local/lib/python2.7/dist-packages/pymodis/downmodis.py", line 392, in connect
    raise Exception("There are some troubles with the server. "
Exception: There are some troubles with the server. The directory seems to be empty
```

Thanks for your help!

**Comment by lucadelu** [comment]
Hi @GloryPassarello ,

the url should not be like yours (`https://e4ftl01.cr.usgs.gov/MOTA/MCD12Q1.051/2013.01.01/`) but only `https://e4ftl01.cr.usgs.gov/`.

Please look the example in the [documentation](http://www.pymodis.org) to be sure about the correct use of pyModis library and scripts, specially for [modis_download_from_list.py](http://www.pymodis.org/scripts/modis_download_from_list.html) pay attention also to the text file syntax

**Comment by lucadelu** [comment]
No activity

Reopen if needed
