### ISSUE TITLE
When I use modis_convert.py to Convert  MYD05_L2 file it says 'Invalid number of pixel 0 for X size 

### ISSUE THREAD

**Issue by cyemeng** [lucadelu/pyModis#98]
`C:\Users\cyeme>modis_convert.py -s "( 0 0 0 0 0 0 1 )" -o f:/guizhou/data/modis/MYD05_L2_reporjection_resample.tif -e 32648 -g 500 f:/guizhou/data/modis/MYD05_L2.A2016041.0600.006.2016041204845.hdf
WxPython missing, no GUI enabled
Traceback (most recent call last):
  File "C:\Users\cyeme\AppData\Local\Programs\Python\Python36\Scripts\modis_convert.py", line 166, in <module>
    main()
  File "C:\Users\cyeme\AppData\Local\Programs\Python\Python36\Scripts\modis_convert.py", line 160, in main
    modisConver.run()
  File "c:\users\cyeme\appdata\local\programs\python\python36\lib\site-packages\pymodis\convertmodis_gdal.py", line 286, in run
    self._createWarped(self.layers[0][0])
  File "c:\users\cyeme\appdata\local\programs\python\python36\lib\site-packages\pymodis\convertmodis_gdal.py", line 205, in _createWarped
    raise Exception('Invalid number of pixel 0 for X size. The '
Exception: Invalid number of pixel 0 for X size. The problem could be in an invalid value of resolution
`
![qq 20171229222045](https://user-images.githubusercontent.com/22722418/34439119-a445f090-ece6-11e7-80df-ce67ee1f97b1.jpg)

**Comment by lucadelu** [comment]
Hi @cyemeng, 
pyModis is not able to work with Level-2 MODIS data, it is able to work with Lavel-3 and probably Level-4 (I never try) . You can find more info about the MODIS Levels [here](https://science.nasa.gov/earth-science/earth-science-data/data-processing-levels-for-eosdis-data-products)
